### ISSUE TITLE
React warning when rendering GeneralSettings

### ISSUE THREAD

**Issue by IDCs** [agc93/vortex-showcase#10]
Vortex 1.3.13
Showcase extension version 0.1.4

The below React warning appears whenever a user switches to the settings page - assigning a unique key for each item rendered inside GeneralSettings should get rid of it. (Please note that ServiceStatusDialog of the BeatVortex extension is raising this error as well)
```
info: Warning: Each child in a list should have a unique "key" prop.%s%s See https://fb.me/react-warning-keys for more information.%s,

Check the render method of `GeneralSettings`.,,
    in option (created by GeneralSettings)
    in GeneralSettings (created by ConnectFunction)
    in ConnectFunction (created by withI18nextTranslation(Connect(GeneralSettings)))
    in withI18nextTranslation(Connect(GeneralSettings)) (created by Settings)
    in div (created by PanelBody)
    in PanelBody (created by Settings)
    in div (created by Panel)
    in Panel (created by Uncontrolled(Panel))
    in Uncontrolled(Panel) (created by ForwardRef)
    in ForwardRef (created by Settings)
    in div (created by Settings)
    in div (created by Settings)
    in div (created by TabPane)
    in Transition (created by Fade)
    in Fade (created by TabPane)
    in TabPane (created by Tab)
    in Tab (created by Settings)
    in div (created by TabContent)
    in TabContent (created by Tabs)
    in div (created by Tabs)
    in TabContainer (created by Tabs)
    in Tabs (created by Uncontrolled(Tabs))
    in Uncontrolled(Tabs) (created by ForwardRef)
    in ForwardRef (created by Settings)
    in div (created by MainPageBody)
    in MainPageBody (created by Settings)
    in div (created by MainPage)
    in MainPage (created by Settings)
    in Settings (created by __ExtendedComponent)
    in __ExtendedComponent (created by ConnectFunction)
    in ConnectFunction (created by withI18nextTranslation(Connect(__ExtendedComponent)))
    in withI18nextTranslation(Connect(__ExtendedComponent)) (created by MainPageContainer)
    in ExtensionGate (created by MainPageContainer)
    in div (created by MainPageContainer)
    in div (created by MainPageContainer)
    in MainPageContainer (created by withI18nextTranslation(MainPageContainer))
    in withI18nextTranslation(MainPageContainer) (created by MainWindow)
    in div (created by DNDContainer)
    in DNDContainer (created by MainWindow)
    in div (created by Flex)
    in div (created by Flex)
    in Flex (created by MainWindow)
    in div (created by FlexLayout)
    in FlexLayout (created by MainWindow)
    in div (created by Flex)
    in div (created by Flex)
    in Flex (created by MainWindow)
    in div (created by FlexLayout)
    in FlexLayout (created by MainWindow)
    in div (created by MainWindow)
    in Suspense (created by MainWindow)
    in MainWindow (created by ConnectFunction)
    in ConnectFunction (created by __ExtendedComponent)
    in __ExtendedComponent
    in I18nextProvider
    in Unknown
    in Provider,
Error:
    at console.error (D:\Projects\basfw\src\renderer.tsx:20:37)
    at printWarning (D:\Projects\basfw\node_modules\react\cjs\react.development.js:315:30)
    at error (D:\Projects\basfw\node_modules\react\cjs\react.development.js:287:5)
    at validateExplicitKey (D:\Projects\basfw\node_modules\react\cjs\react.development.js:1630:5)
    at validateChildKeys (D:\Projects\basfw\node_modules\react\cjs\react.development.js:1656:9)
    at Object.createElementWithValidation (D:\Projects\basfw\node_modules\react\cjs\react.development.js:1806:7)
    at GeneralSettings.render (C:\Users\idcs\AppData\Roaming\vortex_devel\plugins\Vortex Showcase Extension-145-0-1-4-1603555260\webpack:\vortex-showcase\src\settings\Showcas
eSettings.tsx:47:1)
```

**Comment by agc93** [comment]
Thanks @IDCs didn't think of a `select`/`option` element as a list. I'll get that fixed.

**Comment by agc93** [comment]
@IDCs how were you seeing these warnings? I can try and check for these in future, but are they just written to the DevTools console, or do I need to be looking somewhere specific?

**Comment by IDCs** [comment]
Hey @agc93, the warnings would indeed be written to the DevTools console but also to the vortex log files as seen below.
![image](https://user-images.githubusercontent.com/8960252/97178755-db2f3b80-178f-11eb-80ac-29b21d34bea7.png)

**Comment by agc93** [comment]
Excellent, thanks @IDCs I'll have to keep an eye out for that!

I'm just about to push the release fixing this bug, by the way 👍
